#!/bin/bash
#SBATCH -A cs395t_f17 #project group
#SBATCH -J logs/s2c-run           # job name
#SBATCH -o logs/s2c-run.log       # output and error file name (%j expands to jobID)
#SBATCH -n 1 -N 1               # total number of mpi tasks requested
#SBATCH -p gpu     # queue (partition) -- normal, development, etc.
#SBATCH -t 12:00:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=chandana@utexas.edu,pandian@cs.utexas.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

run=2
epochs=4
train=1
load_weights=0
init_epoch=0

img_dim=64
batch_size=128

generator='checkpoint/generator'$run
discriminator='checkpoint/discriminator'$run
output_dir='output'$run

sample=0

if [ "$sample" -eq 0 ]; then
    train_photos='../data/yearbook_train_photos'
    train_sketches='../data/yearbook_train_sketches'
    test_photos='../data/yearbook_test_photos'
else
    train_photos='../data/yearbook_train_photos_sample'
    train_sketches='../data/yearbook_train_sketches_sample'
    test_photos='../data/yearbook_test_photos_sample'
fi

echo '--------------------------------- SBATCH SCRIPT -------------------------------------'
cat ./sbatch_script
echo '-------------------------------------------------------------------------------------'

./run.sh --epochs=$epochs --train=$train --load_weights=$load_weights --initial_epoch=$init_epoch --generator=$generator --discriminator=$discriminator --output_dir=$output_dir --train_photos=$train_photos --train_sketches=$train_sketches --test_photos=$test_photos --img_rows=$img_dim --img_cols=$img_dim --batch_size=$batch_size
